### ISSUE TITLE
AutoComplete not working?

### ISSUE THREAD

**Issue by hsnopi** [dannysteenman/vscode-cloudformation-snippets#12]
**Describe the bug**
When typing cfn nothing pops up. I believe autocomplete is on in the settings. I assume, since no prerequisites are listed, that none are required. Or dod I need to install python or something?

**To Reproduce**
1. open file
2. save as something.yml
3. type cfn
4. nothing pops up

**Expected behavior**
base template should pop up

**Screenshots**

**Desktop (please complete the following information):**
extension Version: v3.33.0
Version: 1.60.2 (user setup)
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:00:31.514Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by crubio1** [comment]
It's not working for me either
v3.37.0
macos 11.6

**Comment by dannysteenman** [comment]
@crubio1 and @hsnopi what happens if you press `ctrl + space` in your editor, does IntelliSense pop up? And if you then type `cfn` do you see the base template?

Also, can you install the intellicode extension to see if IntelliSense invokes correctly? https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode

Looking forward to the results.
