### ISSUE TITLE
No Longer Working on Github Codespaces

### ISSUE THREAD

**Issue by Grunet** [dannysteenman/vscode-cloudformation-snippets#17]
**Describe the bug**
The "cfn" shortcut no longer works in YAML files in Github Codespaces

**To Reproduce**
1. Open a codespace in any Github repository
2. Install the extension
3. Create a YAML file
4. Type "cfn" and note that tabbing does nothing

**Expected behavior**
The skeleton of a CloudFormation template should appear

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux (for codespaces)
 - Visual Studio Code version: 1.90.2
 - CloudFormation Snippets extension version: v5.9.0

**Additional context**
The extension still seems to work on my local VS Code instance

**Comment by dannysteenman** [comment]
Hi @Grunet thanks for opening this gh issue. I've tried to replicate it in a blank github codespace with the extension installed and I noticed the same behaviour in a yaml file. However, json filetypes the autocomplete seems to be working via the extension.

I did some further digging and ran a clean github codespace without extensions enabled and then added a manual snippet for the YAML language (yaml.json):
<img width="626" alt="Screenshot 2024-06-26 at 20 52 40" src="https://github.com/dannysteenman/vscode-cloudformation-snippets/assets/15192660/fc2c1f75-14d3-401d-abd5-f6f808d21884">

If you uncomment the example in the yaml snippet config:
<img width="1116" alt="Screenshot 2024-06-26 at 20 56 37" src="https://github.com/dannysteenman/vscode-cloudformation-snippets/assets/15192660/355a2dbd-13a3-4dfa-a21d-52ffffb6cb4b">

 and try to type "log" in a new yaml file then the autocomplete doesn't trigger as well. 

It seems to be a bug with github codespaces, since the same issue occur without the extension.
