### ISSUE TITLE
Nothing appears when I write cfn

### ISSUE THREAD

**Issue by ManuelZ** [dannysteenman/vscode-cloudformation-snippets#7]
Just installed version 2.24.0 on VSCode 1.50.1

When I write "cfn" after opening the Command Palette, I get nothing... "No matching commands"

**Comment by ghost** [comment]
This is an awesome tool!  Being new to using VSCode, I too was confused by the statement in the description of the extension: ...Usage->Step 3. Type cfn to get the basic template  ......

After a little research into VSCode snippets, I realized that the above might better read:
                 Step 3. Type 'cfn', and then enter CTRL-Space to see the list of snippets in the Command Palette

**Comment by dannysteenman** [comment]
Thanks for the feedback! I'll update the description to make it more clear for new users. As you might've noticed in the GIF that shows the extension in the README, IntelliSense pops up automatically with the suggestions (confirmed with a Macbook Pro) It might be possible that it's not the case for Windows machines. Can you please let me know what OS you're using this extension with? Also, make sure the configured language on the file you're editing is "YAML", otherwise, the extension won't be invoked.

**Comment by ghost** [comment]
Hi Danny:

Specifically I am (and was at the time of my post) running:

macOS 10.15.7
VS Code 1.50.1
CloudFormation YAML Snippets for VS Code 2.24.0

The behavior (which I think is just fine) that I observe is:

The file in question can have either a .yml or a .yaml extension (I’ve tested both).
When one starts typing something which clearly will be recognized by ’Snippets, such as “api”, starting
in the first column of the first line of the empty file, no IntelliSense hints appear. As soon as one types Ctrl-Space
(in this case immediately following the three letters “api”), IntelliSense kicks in.

Thinking that the ’Snippets extension is possibly contextually triggered, I ran the tests again, trying to enter the very first line
of a CF file:  AWSTemplateFormatVersion: '2010-09-09’ - after typing in just “AWST”, there is no IntelliSense, nor once I enter Ctrl-Space.
I then entered the complete line, and tried the “api” test at the very first column of the second line - still no IntelliSense until Ctrl-Space, as well as after
entering <Tab>api, still no IntelliSense until Ctrl-Space is entered.

Again I don’t see this as a problem, but of course you may have a different design intention for the behavior of the extension.

Hope this helps!






On Nov 3, 2020, at 7:27 AM, Danny <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks for the feedback! I'll update the description to make it more clear for new users. As you might've noticed in the GIF that shows the extension in the README, IntelliSense pops up automatically with the suggestions (confirmed with a Macbook Pro) It might be possible that it's not the case for Windows machines. Can you please let me know what OS you're using this extension with? Also, make sure the configured language on the file you're editing is "YAML", otherwise, the extension won't be invoked.

**Comment by dannysteenman** [comment]
I have released a new version (v3.1.0) and updated the Readme with a note that says how to trigger the auto-complete if Intellisense is not being invoked.
