### ISSUE TITLE
Support for auto-complete of Logical ID or Parameters

### ISSUE THREAD

**Issue by tekdj7** [dannysteenman/vscode-cloudformation-snippets#8]
It be great if when doing !Ref or !Sub, for example, provide auto-complete that shows the Parameters/LogicalIDs.  And autocomplete support for Attributes too.

**Comment by ojarosch** [comment]
You might want to take a look at this: 
https://github.com/keyboardDrummer/cloudformation-ide-tooling

**Comment by tekdj7** [comment]
@fastplayer95 thanks for the suggestion. I don't recall all the differences between that solution and this one. However, I did open an issue against that solution being incomplete. See [here](https://github.com/keyboardDrummer/cloudformation-ide-tooling/issues/18).

**Comment by dannysteenman** [comment]
Yes it's a bit out of scope for this extension since the snippets are all generated and static. If you'd like a more dynamic autocomplete/reference in vscode when building infrastructure on AWS, I would highly recommend to switch to AWS CDK (TypeScript): https://docs.aws.amazon.com/cdk/v2/guide/work-with-cdk-typescript.html
